<?php

/**
 * @file
 * The main functionality for this module.
 */

function tripal_citation_menu() {
  // Configure Tripal Citation.
  $items['admin/tripal/extension/tripal_citation/configure'] = array(
    'title' => t('Tripal Citation Configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tripal_citation_configure_form'),
    'access arguments' => array('administer tripal'),
    'file' => 'includes/forms/tripal_citation_configure.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}