<?php

/**
 * @file
 * The main functionality for this module.
 */

// Prepare term used by field.
module_load_include('inc', 'tripal_citation', 'includes/TripalFields/tripal_citation.fields');
// Include Tirpal Citation API.
module_load_include('inc', 'tripal_citation', 'api/tripal_citation.api');

function tripal_citation_menu() {
  $items = array();

  // Configure Tripal Citation.
  $items['admin/tripal/extension/tripal_citation/configure'] = array(
    'title' => t('Tripal Citation Configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tripal_citation_configure_form'),
    'access arguments' => array('administer tripal'),
    'file' => 'includes/forms/tripal_citation_configure.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_theme().
 * Theme citations.
 * 
 * @see theme/tripal_citation_citation.tpl.php
 */
function tripal_citation_theme($existing, $type, $theme, $path) {
  $items = array();

  $items['tripal_citation_citation'] = array(
    'template' => 'tripal_citation_citation',
    'path' => $path . '/theme',
    'variables' => array()
  );

  return $items;
}
